---
#  - name: Create user-defined network
- name: Create and start services
  community.docker.docker_compose:
    project_src: ./
    register: output

- ansible.builtin.debug:
    var: output.stdout_lines
